import type { Metadata } from "next";
import { Roboto, Inter } from 'next/font/google'
import "./globals.css";
import { cn } from "@/lib/utils";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: "400"
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(`bg-background min-h-screen antialiased`, roboto.className)}
      >
        {children}
      </body>
    </html>
  );
}
